"""Add primary key constraints for association tables, authority for tweets

Revision ID: 0389392410d1
Revises: 0b1c1f2cfd5d
Create Date: 2024-06-25 21:58:36.185086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0389392410d1'
down_revision: Union[str, None] = '0b1c1f2cfd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('follow', 'follower',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('like', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tweet', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tweet', 'user', ['author_id'], ['id'])
    op.create_primary_key("pk_follow", "follow", ["user", "follower"])
    op.create_primary_key("pk_like", "like", ["user_id", "tweet_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_like", "like")
    op.drop_constraint("pk_follow", "follow")
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'author_id')
    op.alter_column('like', 'tweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follow', 'follower',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('follow', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
