"""Add  authority for media

Revision ID: 09589b667c08
Revises: bdba43c3c325
Create Date: 2024-07-02 11:36:42.126511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09589b667c08'
down_revision: Union[str, None] = 'bdba43c3c325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('auhor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'media', 'user', ['auhor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'auhor_id')
    # ### end Alembic commands ###
