"""Add tweet creation date, Follow model add instead of table, 
Unique constraint for user.api_key

Revision ID: bdba43c3c325
Revises: a68d6c0d09d3
Create Date: 2024-06-26 18:06:31.841836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdba43c3c325'
down_revision: Union[str, None] = '0389392410d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('creation_date', sa.DateTime(), nullable=False))
    op.add_column('follow', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.add_column('follow', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('follow_user_fkey', 'follow', type_='foreignkey')
    op.drop_constraint('follow_follower_fkey', 'follow', type_='foreignkey')
    op.create_foreign_key("fk_follower_id", 'follow', 'user', ['follower_id'], ['id'])
    op.create_foreign_key("fk_user_id", 'follow', 'user', ['user_id'], ['id'])
    op.drop_column('follow', 'user')
    op.drop_column('follow', 'follower')
    op.create_unique_constraint("u_api_key", "user", ["api_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("u_api_key", "user")
    op.add_column('follow', sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follow', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint("fk_user_id", 'follow', type_='foreignkey')
    op.drop_constraint("fk_follower_id", 'follow', type_='foreignkey')
    op.create_foreign_key('follow_follower_fkey', 'follow', 'user', ['follower'], ['id'])
    op.create_foreign_key('follow_user_fkey', 'follow', 'user', ['user'], ['id'])
    op.drop_column('follow', 'user_id')
    op.drop_column('follow', 'follower_id')
    op.drop_column('tweet', 'creation_date')
    # ### end Alembic commands ###
